apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mapdoon
  namespace: appdoon
spec:
  interval: 1m
  path: ./arvan/appdoon/mapdoon/manifests
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
