---
- name: Deploy Mapdoon Backend
  hosts: mapdoon
  become: yes
  become_user: ubuntu

  tasks:
    - name: Git fetch
      command: git fetch --all
      args:
        chdir: ~/mapdoon/backend

    - name: Git checkout main
      command: git checkout add-containerization
      args:
        chdir: ~/mapdoon/backend

    - name: Git pull origin main
      command: git pull origin add-containerization
      args:
        chdir: ~/mapdoon/backend

    - name: Build and Deploy the project using Docker Compose
      command: sudo docker compose up --build -d
      args:
        chdir: ~/mapdoon/backend/Src

    - name: Show the status of the containers
      command: sudo docker compose ps
      args:
        chdir: ~/mapdoon/backend/Src
      register: docker_ps_output

    - name: Print Docker PS Output
      debug:
        var: docker_ps_output.stdout_lines
