services:
  appdoon:
   image: appdoon:v1
   build: .
   container_name: appdoon_backend
   hostname: appdoon_backend
   networks:
    - appdoon_network
   ports:
     - "5000:5000"
   env_file:
     - .env.local
   restart: on-failure
   depends_on:
     - database

  database:
    image: mcr.microsoft.com/mssql/server
    user: root
    volumes:
      - appdoon_db_data:/var/opt/mssql/data
    env_file:
      - .env.local
    ports:
      - "1433:1433"
    container_name: appdoon_database
    hostname: appdoon_database
    networks:
    - appdoon_network

  minio:
    image: "minio/minio:RELEASE.2022-11-11T03-44-20Z"
    volumes:
      - minio_storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.local
    command: server --console-address ":9001" /data
    container_name: mapdoon_minio
    networks:
      - appdoon_network
volumes:
  appdoon_db_data:
  minio_storage:
networks:
    appdoon_network:
